version: "3.7"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: ${DATABASE_RESTART:-no}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT:-3306}:${DATABASE_PORT:-3306}
  # web:
  #   image: venapi
  #   depends_on:
  #     - db
  #   ports:
  #     - ${PORT}:${PORT}
volumes:
  db_data:
